---
VERSAO: "1.3.1"
URL: "https://github.com/prometheus/node_exporter/releases/download/v{{ VERSAO }}/node_exporter-{{ VERSAO }}.linux-amd64.tar.gz"
SERVICO: "node_exporter"
DESTINO: "/usr/local/bin/"
LICENSE: "node_exporter-{{ VERSAO }}.linux-amd64/LICENSE"
NOTICE: "node_exporter-{{ VERSAO }}.linux-amd64/NOTICE"
USUARIO: "node_exporter"
GRUPO: "node_exporter"
PERMISSAO: "0775"
SHELL: "/bin/false"
